/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libralog;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class AddBooks extends javax.swing.JFrame {

    /**
     * Creates new form AddBooks
     */
    public AddBooks() {
        initComponents();
        this.setSize(1000, 520);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        
        this.setTitle("Add Books | LibraLog");
        this.setIconImage(new ImageIcon(getClass().getResource("assets/original/books.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbViewBooks = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtBookTitle = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnAddNow = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        backBtn1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btnLogout1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(71, 74, 79));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Poppins Black", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(190, 199, 224));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LibraLog - View Books");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 30, 370, 40);

        jPanel5.setBackground(new java.awt.Color(50, 67, 72));
        jPanel5.setLayout(null);

        tbViewBooks.setBackground(new java.awt.Color(71, 99, 129));
        tbViewBooks.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        tbViewBooks.setForeground(new java.awt.Color(147, 192, 202));
        tbViewBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book ID", "Book Title", "Author Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbViewBooks);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 720, 270);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(37, 115, 720, 270);

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(101, 106, 184));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Come & Check Our LibraLog Books. Everyone Can Read!");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 70, 600, 30);

        backBtn.setBackground(new java.awt.Color(60, 54, 51));
        backBtn.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        backBtn.setForeground(new java.awt.Color(170, 204, 230));
        backBtn.setText("Back");
        backBtn.setBorder(null);
        jPanel1.add(backBtn);
        backBtn.setBounds(600, 30, 120, 40);

        jLabel16.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(238, 237, 235));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("For more information, contact us at email @: library@LibraLog.com");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(40, 410, 540, 30);

        submitBtn.setBackground(new java.awt.Color(81, 114, 149));
        submitBtn.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(170, 215, 230));
        submitBtn.setText("Submit");
        submitBtn.setBorder(null);
        jPanel1.add(submitBtn);
        submitBtn.setBounds(780, 120, 170, 40);

        btnLogout.setBackground(new java.awt.Color(60, 54, 51));
        btnLogout.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(170, 204, 230));
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        jPanel1.add(btnLogout);
        btnLogout.setBounds(740, 30, 120, 40);

        jPanel2.setBackground(new java.awt.Color(71, 74, 79));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Poppins Black", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(190, 199, 224));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LibraLog - Add Books");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 30, 370, 40);

        jPanel6.setBackground(new java.awt.Color(50, 67, 72));
        jPanel6.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(238, 237, 235));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Book Title:");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(60, 80, 100, 30);

        txtBookTitle.setBackground(new java.awt.Color(100, 108, 116));
        txtBookTitle.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        txtBookTitle.setForeground(new java.awt.Color(224, 205, 210));
        txtBookTitle.setAlignmentX(0.0F);
        txtBookTitle.setAlignmentY(-0.0F);
        txtBookTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(txtBookTitle);
        txtBookTitle.setBounds(180, 80, 290, 33);

        txtAuthor.setBackground(new java.awt.Color(100, 108, 116));
        txtAuthor.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        txtAuthor.setForeground(new java.awt.Color(224, 205, 210));
        txtAuthor.setAlignmentX(0.0F);
        txtAuthor.setAlignmentY(0.0F);
        txtAuthor.setAutoscrolls(false);
        txtAuthor.setBorder(null);
        jPanel6.add(txtAuthor);
        txtAuthor.setBounds(180, 130, 210, 33);

        txtQuantity.setBackground(new java.awt.Color(100, 108, 116));
        txtQuantity.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        txtQuantity.setForeground(new java.awt.Color(224, 205, 210));
        txtQuantity.setAlignmentX(0.0F);
        txtQuantity.setAlignmentY(-0.0F);
        txtQuantity.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(txtQuantity);
        txtQuantity.setBounds(410, 30, 60, 33);

        jLabel18.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(238, 237, 235));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Author:");
        jLabel18.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel6.add(jLabel18);
        jLabel18.setBounds(70, 130, 110, 30);

        jLabel19.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(238, 237, 235));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Book Quantity (Copies Available): ");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(60, 30, 320, 30);

        btnAddNow.setBackground(new java.awt.Color(81, 114, 149));
        btnAddNow.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        btnAddNow.setForeground(new java.awt.Color(170, 215, 230));
        btnAddNow.setText("Add Now");
        btnAddNow.setBorder(null);
        btnAddNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNowActionPerformed(evt);
            }
        });
        jPanel6.add(btnAddNow);
        btnAddNow.setBounds(40, 190, 230, 40);

        jLabel7.setFont(new java.awt.Font("Poppins Black", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(224, 204, 190));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\Documents\\NetBeansProjects\\LibraLog\\src\\libralog\\assets\\home_book.png")); // NOI18N
        jLabel7.setToolTipText("");
        jLabel7.setDoubleBuffered(true);
        jPanel6.add(jLabel7);
        jLabel7.setBounds(510, 20, 210, 220);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(37, 115, 750, 270);

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(101, 106, 184));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Staffs/Admins Can Add New Books To The Collections.");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 70, 600, 30);

        backBtn1.setBackground(new java.awt.Color(60, 54, 51));
        backBtn1.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        backBtn1.setForeground(new java.awt.Color(170, 204, 230));
        backBtn1.setText("Back");
        backBtn1.setBorder(null);
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(backBtn1);
        backBtn1.setBounds(600, 30, 120, 40);

        jLabel17.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(238, 237, 235));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("For more information, contact us at email @: library@LibraLog.com");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(40, 410, 540, 30);

        btnLogout1.setBackground(new java.awt.Color(60, 54, 51));
        btnLogout1.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        btnLogout1.setForeground(new java.awt.Color(170, 204, 230));
        btnLogout1.setText("Logout");
        btnLogout1.setBorder(null);
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout1);
        btnLogout1.setBounds(740, 30, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        StaffMainMenu smm = new StaffMainMenu();
        this.setVisible(false);
        smm.setVisible(true);

    }//GEN-LAST:event_backBtn1ActionPerformed

    private void btnAddNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNowActionPerformed
        // Assuming you have text fields named txtTitle, txtAuthor, and txtCopies for user input
        String title = txtBookTitle.getText();
        String author = txtAuthor.getText();

        // Check if the 'Copies' field is a valid integer
        int copies;
        try {
            copies = Integer.parseInt(txtQuantity.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for copies.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Clear the input fields if needed
        txtBookTitle.setText("");
        txtAuthor.setText("");
        txtQuantity.setText("");
        
        // Check if title, author, and copies are not empty
        if (!title.isEmpty() && !author.isEmpty() && copies > 0) {
            // Call the addBook method to add the book to the database
            BookManagement.addBook(title, author, copies);

            // Display a success message or perform additional actions if needed
            JOptionPane.showMessageDialog(this, "Book added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Clear the input fields if needed
            txtBookTitle.setText("");
            txtAuthor.setText("");
            txtQuantity.setText("");
        } else {
            // Display an error message if any field is empty or copies is not a positive number
            JOptionPane.showMessageDialog(this, "Please enter valid values for title, author, and copies.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_btnAddNowActionPerformed

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        Home hm = new Home();
        this.setVisible(false);
        hm.setVisible(true);
    }//GEN-LAST:event_btnLogout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton btnAddNow;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTable tbViewBooks;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtBookTitle;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
