/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libralog;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Daniel
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setSize(770, 450);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        
        this.setTitle("Home | LibraLog");
        this.setIconImage(new ImageIcon(getClass().getResource("assets/original/books.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(770, 450));
        setPreferredSize(new java.awt.Dimension(770, 450));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(116, 114, 100));
        jPanel1.setMaximumSize(new java.awt.Dimension(770, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(770, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(770, 450));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Poppins", 3, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(170, 215, 217));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("@ DPTF 2024");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 360, 120, 30);

        jLabel2.setFont(new java.awt.Font("Poppins Black", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(224, 204, 190));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\Documents\\NetBeansProjects\\LibraLog\\src\\libralog\\assets\\home_book.png")); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setDoubleBuffered(true);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(430, 110, 310, 270);

        jLabel3.setFont(new java.awt.Font("Poppins Black", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(224, 204, 190));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LibraLog");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 30, 150, 40);

        jButton1.setBackground(new java.awt.Color(60, 54, 51));
        jButton1.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(229, 225, 218));
        jButton1.setText("Login As Staff");
        jButton1.setBorder(null);
        jPanel1.add(jButton1);
        jButton1.setBounds(90, 270, 260, 40);

        jButton2.setBackground(new java.awt.Color(60, 54, 51));
        jButton2.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(229, 225, 218));
        jButton2.setText("Register Account");
        jButton2.setBorder(null);
        jPanel1.add(jButton2);
        jButton2.setBounds(90, 150, 260, 40);

        jButton3.setBackground(new java.awt.Color(60, 54, 51));
        jButton3.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(229, 225, 218));
        jButton3.setText("Login As Student");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(90, 210, 260, 40);

        jButton4.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jButton4.setText("Register Account");
        jPanel1.add(jButton4);
        jButton4.setBounds(90, 210, 260, 40);

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(224, 205, 210));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("User-Friendly Library Management System for School Libraries.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 70, 600, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-20, 0, 810, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
