/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libralog;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Daniel
 */
public class MyBookHistory extends javax.swing.JFrame {

    /**
     * Creates new form MyBookHistory
     */
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    
    public MyBookHistory() {
        initComponents();
        this.setSize(850, 650);
//        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        
        this.setTitle("My Book History | LibraLog");
        this.setIconImage(new ImageIcon(getClass().getResource("assets/original/books.jpg")).getImage());
        
        // View Books Table
        tbPastBooks.getTableHeader().setFont(new Font("Poppins", Font.BOLD, 16));
        tbPastBooks.getTableHeader().setBackground(new Color(36,56,62));
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Book ID");
        tableModel.addColumn("Book Title");
        tableModel.addColumn("Author");
        tableModel.addColumn("Status");
        tableModel.addColumn("Date & Time");
        tbPastBooks.setModel(tableModel);
     
        // Set connection 
        
        con = db.mycon();
        
        // Retrieve Books Information from Books
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/libralog", "root", "")) {
            String sql = "SELECT * FROM pasthistory";
            try (PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
                try (ResultSet resultSet = preparedStatement.executeQuery()) {
                    // Iterate through the result set and add rows to the DefaultTableModel
                    tableModel.setRowCount(0); // Clear existing rows

                    while (resultSet.next()) {
                        // Add each row of book information to the DefaultTableModel
                        Object[] row = {
                            resultSet.getInt("bookID"),
                            resultSet.getString("title"),
                            resultSet.getString("author"),
                            resultSet.getString("status"),
                            resultSet.getString("date_time")
                        };
                        tableModel.addRow(row);
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            System.err.println("Failed to view books.");
        }
        con = db.mycon();
    }

    
    MyBookHistory(String sid) {
        this();
        showStudentID.setText(sid);
        showStudentID.setVisible(false);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        showStudentID = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPastBooks = new javax.swing.JTable();
        btnSearchNow = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtSearchBook = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(116, 114, 100));
        jPanel1.setForeground(new java.awt.Color(224, 205, 210));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 600));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Poppins Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(224, 204, 190));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LibraLog");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 40, 190, 40);

        showStudentID.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        showStudentID.setForeground(new java.awt.Color(224, 226, 152));
        showStudentID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(showStudentID);
        showStudentID.setBounds(410, 20, 190, 30);

        jLabel16.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(238, 237, 235));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("If any problem, email help@libralog.com");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 600, 380, 30);

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(224, 205, 210));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("My Past Book History");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(140, 70, 640, 30);

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(224, 205, 210));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Here Are Your Borrowed/Past Books From LibraLog Library:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 100, 600, 30);

        btnBack.setBackground(new java.awt.Color(60, 54, 51));
        btnBack.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        btnBack.setForeground(new java.awt.Color(224, 205, 210));
        btnBack.setText("Back");
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(670, 80, 120, 40);

        tbPastBooks.setBackground(new java.awt.Color(60, 54, 51));
        tbPastBooks.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbPastBooks.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        tbPastBooks.setForeground(new java.awt.Color(224, 205, 210));
        tbPastBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Book ID", "Book Title", "Author Name", "Quantity", "Status", "Date & Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbPastBooks);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(40, 150, 720, 270);

        btnSearchNow.setBackground(new java.awt.Color(149, 119, 81));
        btnSearchNow.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        btnSearchNow.setForeground(new java.awt.Color(230, 208, 170));
        btnSearchNow.setText("Search Now");
        btnSearchNow.setBorder(null);
        btnSearchNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNowActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchNow);
        btnSearchNow.setBounds(420, 530, 340, 40);

        jLabel15.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(230, 208, 170));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Search Book Name");
        jLabel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(490, 440, 200, 30);

        txtSearchBook.setBackground(new java.awt.Color(60, 54, 51));
        txtSearchBook.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        txtSearchBook.setForeground(new java.awt.Color(224, 205, 210));
        txtSearchBook.setAlignmentX(0.0F);
        txtSearchBook.setAlignmentY(0.0F);
        txtSearchBook.setAutoscrolls(false);
        txtSearchBook.setBorder(null);
        jPanel1.add(txtSearchBook);
        txtSearchBook.setBounds(540, 480, 220, 33);

        jLabel17.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(238, 237, 235));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Book Title:");
        jLabel17.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(420, 480, 110, 30);

        jLabel4.setFont(new java.awt.Font("Poppins Black", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(224, 204, 190));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\danie\\Documents\\NetBeansProjects\\LibraLog\\src\\libralog\\assets\\home_book.png")); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.setDoubleBuffered(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 450, 350, 130);

        btnLogout.setBackground(new java.awt.Color(60, 54, 51));
        btnLogout.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(224, 205, 210));
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout);
        btnLogout.setBounds(670, 30, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        String studentID = showStudentID.getText();
        
        // Passing Student ID value to Main Menu.
        this.setVisible(false);
        MainMenu mm = new MainMenu(studentID);
        mm.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNowActionPerformed
        String filter = txtSearchBook.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>((DefaultTableModel) tbPastBooks.getModel());
        tbPastBooks.setRowSorter(trs);

        if (filter.trim().length() == 0) {
            trs.setRowFilter(null);
        } else {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + filter));
        }
    }//GEN-LAST:event_btnSearchNowActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
      LoginStudent ls = new LoginStudent();
      this.setVisible(false);
      this.dispose();
      ls.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyBookHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyBookHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyBookHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyBookHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyBookHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearchNow;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel showStudentID;
    private javax.swing.JTable tbPastBooks;
    private javax.swing.JTextField txtSearchBook;
    // End of variables declaration//GEN-END:variables
}
