/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libralog;

/**
 *
 * @author Daniel
 */
public class MyBookHistory extends javax.swing.JFrame {

    /**
     * Creates new form MyBookHistory
     */
    public MyBookHistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        showStudentID = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbViewBooks = new javax.swing.JTable();
        btnSearchNow = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtSearchBook = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        backBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(116, 114, 100));
        jPanel1.setForeground(new java.awt.Color(224, 205, 210));
        jPanel1.setMinimumSize(new java.awt.Dimension(850, 600));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Poppins Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(224, 204, 190));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LibraLog");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 40, 190, 40);

        showStudentID.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        showStudentID.setForeground(new java.awt.Color(224, 226, 152));
        showStudentID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(showStudentID);
        showStudentID.setBounds(410, 20, 190, 30);

        jLabel16.setFont(new java.awt.Font("Poppins", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(238, 237, 235));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("If any problem, email help@libralog.com");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 600, 380, 30);

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(224, 205, 210));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("My Past Book History");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(140, 70, 640, 30);

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(224, 205, 210));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Here Are Your Borrowed/Past Books From LibraLog Library:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 100, 600, 30);

        backBtn.setBackground(new java.awt.Color(60, 54, 51));
        backBtn.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        backBtn.setForeground(new java.awt.Color(224, 205, 210));
        backBtn.setText("Logout");
        backBtn.setBorder(null);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(630, 30, 120, 40);

        tbViewBooks.setBackground(new java.awt.Color(60, 54, 51));
        tbViewBooks.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tbViewBooks.setFont(new java.awt.Font("Poppins", 0, 16)); // NOI18N
        tbViewBooks.setForeground(new java.awt.Color(224, 205, 210));
        tbViewBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book ID", "Book Title", "Author Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbViewBooks);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(40, 150, 720, 270);

        btnSearchNow.setBackground(new java.awt.Color(149, 119, 81));
        btnSearchNow.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        btnSearchNow.setForeground(new java.awt.Color(230, 208, 170));
        btnSearchNow.setText("Search Now");
        btnSearchNow.setBorder(null);
        btnSearchNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNowActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchNow);
        btnSearchNow.setBounds(420, 530, 340, 40);

        jLabel15.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(230, 208, 170));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Search Book Name");
        jLabel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(490, 440, 200, 30);

        txtSearchBook.setBackground(new java.awt.Color(60, 54, 51));
        txtSearchBook.setFont(new java.awt.Font("Poppins", 1, 16)); // NOI18N
        txtSearchBook.setForeground(new java.awt.Color(224, 205, 210));
        txtSearchBook.setAlignmentX(0.0F);
        txtSearchBook.setAlignmentY(0.0F);
        txtSearchBook.setAutoscrolls(false);
        txtSearchBook.setBorder(null);
        jPanel1.add(txtSearchBook);
        txtSearchBook.setBounds(540, 480, 220, 33);

        jLabel17.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(238, 237, 235));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Book Title:");
        jLabel17.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(420, 480, 110, 30);

        backBtn1.setBackground(new java.awt.Color(60, 54, 51));
        backBtn1.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        backBtn1.setForeground(new java.awt.Color(224, 205, 210));
        backBtn1.setText("Back");
        backBtn1.setBorder(null);
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn1);
        backBtn1.setBounds(630, 80, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        StaffLogin sl = new StaffLogin();
        this.setVisible(false);
        sl.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnSearchNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNowActionPerformed
        String filter = txtSearchBook.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>((DefaultTableModel) tbViewBooks.getModel());
        tbViewBooks.setRowSorter(trs);

        if (filter.trim().length() == 0) {
            trs.setRowFilter(null);
        } else {
            trs.setRowFilter(RowFilter.regexFilter("(?i)" + filter));
        }
    }//GEN-LAST:event_btnSearchNowActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        MainMenu mm = new MainMenu();
        this.setVisible(false);
        mm.setVisible(true);

    }//GEN-LAST:event_backBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyBookHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyBookHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyBookHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyBookHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyBookHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton btnSearchNow;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel showStudentID;
    private javax.swing.JTable tbViewBooks;
    private javax.swing.JTextField txtSearchBook;
    // End of variables declaration//GEN-END:variables
}
